language: node_js
sudo: required
services:
  - docker
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
before_script:
  - echo "Branch... $TRAVIS_BRANCH"
  - echo "HEROKU_APP_NAME... $HEROKU_APP_NAME"
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin registry-1.docker.io
  - docker build -t registry.heroku.com/chronacc-tr/web .
script:
  - bash showInfo.sh
  - cd $TRAVIS_BUILD_DIR/client
  - npm i
  - npm run build
  - npm run start:ci &
  - cypress run --record --key $CYPRESS_RECORD_KEY --env apiUrl=https://chronacc-tr.herokuapp.com/api --browser chrome
  - kill $(jobs -p) || true
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME;
    fi
