version: "2"
services:
    client:
        image: webapp-client
        restart: always
        ports:
            - "8090:8090"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - server
        networks:
            - webappnetwork
    server:
        image: webapp-server
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge